version: '2'

services:
    app:
        build: app
        ports:
            - "8080:80"
            - "8443:443"
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
        volumes:
            - app_data:/var/www/html
    postgres:
        build: postgres
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
        ports:
            - "5432:5432"
        command: postgres -c log_statement=all
        volumes:
            - postgres_data:/var/lib/postgresql/data
            
#    postgres96:
#        build: postgres96
#        environment:
#            - TZ=Asia/Tokyo
#            - LANG=ja_JP.UTF-8
#        ports:
#            - "5433:5432"
#        volumes:
#            - postgres96_data:/var/lib/postgresql/data
    
    mysql:
        image: mysql:5.7
        environment:
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
            
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    mail:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
            
    sftp:
        image: atmoz/sftp
        privileged: true
        ports:
            - "2222:22"
        command: 'sftp:pass:33:33:upload'
        volumes:
             - app_data:/home/sftp/upload

volumes:
    app_data:
    postgres_data:
    postgres96_data:
    mysql_data:

